### ISSUE TITLE
What about adding this stuff to the core?

### ISSUE THREAD

**Issue by mlocati** [concrete5cojp/concrete5-redis-override#1]
I find this Redis-related stuff really great. Do you mind if I suggest to add these classes to the concrete5 core (with just minor changes)?

**Comment by deek87** [comment]
To be fair, I havent tested this version yet with the session prefixing... 

There are some minor changes needed like you need to add a ttl (for the server connection )- as the redis driver sets it to 0.1 seconds which on AWS isnt always long enough across AZs

I do have a version available that doesnt use session prefixing and 100% works. I'll update this and add a branch that doesnt use session prefixing

**Comment by mlocati** [comment]
> I do have a version available that doesnt use session prefixing and 100% works.

I think we need session prefixing, because the same redis server could be used by different c5 installations.
What if we use `md5(DIR_APPLICATION)` as session prefix by default?

**Comment by deek87** [comment]
Actually sessions dont need prefix's its the cache that needs it as the cache calls ->flush() and if no prefix is added it will clear the session data. 

But I've updated the code to a verified working version now. If there is interest in redis for c5 core, then I'll create a core version PR

**Comment by mlocati** [comment]
> If there is interest in redis for c5 core, then I'll create a core version PR

I certainly would :+1: such a PR (but of course I'm not a member of PL).

**Comment by aembler** [comment]
Yeah there is definite interest. It looks great!

We have a super bare bones redis client library in the release/9.0.0 branch to handle some event publish/subscribe but your implementation looks much more complete (also it would be really nice to have redis available as a session handler, page cache and cache/expensive driver). 

We’d definitely accept it in the core

**Comment by mlocati** [comment]
Stash already supports redis, but we are missing session and page cache

**Comment by deek87** [comment]
@mlocati Stash's redis driver just deletes the DB (sometimes this doesnt flush correctly, especially in cluster cases) and doesnt allow prefixing - thats why I had to create the new one

I'll get round to a PR sometime this week, I'll also add the Redis Cluster Driver

**Comment by mlocati** [comment]
Fixed by https://github.com/concrete5/concrete5/pull/7206 ?

**Comment by deek87** [comment]
indeed, thanks for reminded me 👍
